import type { Scheme } from "@/lib/schemes";

export const categoryConfig = {
  pensions: { name: "Pensions", title: "Punjab Pension Schemes 2026 – Old Age, Widow Pension, Apply & Status", description: "Punjab pension schemes 2026: old age pension, widow pension, online apply guidance, forms, eligibility, pension amount, beneficiary list and status check.", intro: "Looking for old age pension Punjab, widow pension in Punjab, pension status, online application or pension forms? Compare the Punjab social-security pension guides here, then check eligibility, documents, amount information and the official application or status route." },
  scholarships: { name: "Scholarships", title: "Punjab Scholarship Schemes 2026", description: "Find Punjab scholarship and education-support schemes with eligibility, document and application guidance.", intro: "Browse verified education-support programmes for Punjab students. Published guides distinguish official eligibility and current application routes from older or unverified information." },
  "women-and-children": { name: "Women & Children", title: "Punjab Schemes for Women and Children 2026", description: "Explore Punjab government schemes for women and children, including financial assistance, pensions and family support.", intro: "Find Punjab programmes supporting women, children and household financial security. Use the guides to compare benefits, eligibility evidence and authorized registration channels." },
  agriculture: { name: "Agriculture", title: "Punjab Agriculture Schemes 2026", description: "Verified Punjab agriculture scheme guidance for farmers and rural households.", intro: "This category will contain agriculture schemes only after current rules and official application sources have been verified." },
  "children-and-families": { name: "Children & Families", title: "Punjab Family Benefit & Dependent Children Pension Schemes 2026", description: "Punjab dependent children pension and National Family Benefit Scheme guides: check ₹1,500 pension, BPL eligibility, forms, documents, apply online and status.", intro: "Find Punjab assistance for dependent children and BPL families after the death or incapacity of a parent or main breadwinner. These guides explain pension amounts, age and family conditions, forms, required documents, online application and status guidance." },
  disability: { name: "Disability", title: "Disability Pension Punjab 2026 – ₹1,500, Eligibility, Form & Apply", description: "Punjab disability or handicap pension 2026: check ₹1,500 amount, 50% disability rule, income limit, pension form, documents and online application.", intro: "Check Punjab disability pension, also searched as handicap pension or handicapped pension in Punjab. The guide covers the monthly amount, disability percentage, family-income rule, pension form, documents and online or offline application routes." },
  "construction-workers": { name: "Construction Workers", title: "Punjab BOCW & Labour Card Schemes 2026 – Status, Scholarship & Benefits", description: "Punjab BOCW and labour card schemes: registration/status guidance, scholarship, Shagun, maternity and tool-kit benefits for construction workers.", intro: "Looking for Punjab labour card status check online, BOCW Punjab scholarship, Shagun Scheme or construction-worker benefits? Punjab Building and Other Construction Workers Welfare Board schemes generally require active registration and contributions; compare the benefit guides and required documents here." },
  health: { name: "Health", title: "Punjab Health Schemes 2026", description: "Find verified Punjab health-scheme guidance, including eligibility, health-card registration, cashless treatment and official hospital checks.", intro: "Explore Punjab healthcare programmes with practical guidance on registration, health cards, empanelled hospitals and cashless treatment. Always confirm that the proposed treatment package is authorized before admission." },
} as const;

export type CategorySlug = keyof typeof categoryConfig;

export function categorySlugFor(category: Scheme["category"]): CategorySlug {
  return category.toLowerCase().replaceAll(" & ", "-and-").replaceAll(" ", "-") as CategorySlug;
}
