export const schemeDeepDives: Record<string, { heading: string; paragraphs: string[] }> = {
  "mukh-mantri-mawan-dheeyan-satkar-yojana": {
    heading: "Understanding the Satkar Yojana exclusions and DBT",
    paragraphs: [
      "This scheme has broad coverage, but its exclusions need careful reading. The Gazette excludes a woman who is a regular or retired government employee, specified regular or retired public-body employees drawing pension, a person who paid any income tax in the previous financial year, and a serving or former minister, MP or MLA. The spouse of a serving minister, MP or MLA is also excluded. These are applicant-level tests. The notification does not say that every woman in a household becomes ineligible merely because another family member has employment or income, except for the specifically stated spouse rule. Applicants should answer the registration questions exactly as framed and seek official clarification for an unusual employment or pension situation.",
      "The bank requirement deserves equal attention because the benefit is designed for Aadhaar-based DBT. The woman should hold or use an account in which her identity details match her Aadhaar record. Before relying on the account, she can ask the branch whether it is active, whether KYC is complete, and whether it is the account mapped for Aadhaar payments. Scheduled Caste applicants should also ensure that their caste certificate is valid and legible because it supports the higher monthly amount. Registration at designated centres is free, and a demand for payment, an OTP, a PIN or a remote-access app should be treated as a warning sign rather than part of the official process.",
    ],
  },
  "old-age-pension-punjab": {
    heading: "Age, income, residence and property verification",
    paragraphs: [
      "An old-age pension application usually brings together several kinds of evidence. Age proof establishes that the applicant meets the prescribed age rule; address evidence supports Punjab residence; bank evidence identifies the payment destination; and the department's income and property checks determine whether the person falls within the current means-based conditions. These checks should not be confused with one another. For example, a voter or Aadhaar record may help establish identity and address but may not prove age to the department's satisfaction in every case. Applicants who lack a straightforward birth record should ask which alternative age documents are currently accepted before submitting a collection of informal papers.",
      "The most important gap in the current service sheet is that it does not reproduce every operative threshold or the pension amount. This is why this page does not borrow a number from an old news report. At a Sewa Kendra, the applicant should ask the operator to show or state the current age, annual-income and property criteria associated with the service. If land or property is jointly held, inherited, disputed or recorded under an old family entry, explain that before the verification stage. A complete and truthful application is safer than assuming that an official database will interpret a complicated ownership record in the applicant's favour without supporting context.",
    ],
  },
  "widow-destitute-pension-punjab": {
    heading: "Choosing the correct evidence for the applicant's situation",
    paragraphs: [
      "The official service sheet groups several circumstances under one pension service, but their evidence is not interchangeable. A widow normally relies on the husband's registered death certificate. A divorced applicant may need the legally recognized divorce order. A woman whose husband is missing may need the police record specified by the department, while a claim connected with a spouse's disability requires the accepted disability evidence. The applicant should not select whichever category appears easiest to document. The category must describe her actual circumstances, and the names, dates and relationships in the supporting record should agree with her identity and family details.",
      "Some cases need additional preparation. A death certificate may carry a spelling that differs from the widow's documents; a court order may use a former address; or an FIR may not contain enough information to connect the missing person to the applicant. These issues do not necessarily mean that the woman is ineligible, but they may require correction or another supporting record from the competent authority. Ask the Sewa Kendra what evidence is accepted for the exact category and whether self-attestation, certified copies or originals are required. Keep a full copy of the submitted packet because a later query is much easier to answer when the applicant can see precisely what the department received.",
    ],
  },
  "dependent-children-pension-punjab": {
    heading: "How a parent or guardian should prepare the child's case",
    paragraphs: [
      "This pension is assessed through both the child's details and the circumstances of the adult applying on the child's behalf. Begin by making a list of every child included, with the full name and date of birth exactly as shown on the birth or school record. Then identify whether the case is being presented by the mother, father or another guardian and which parental death or disability condition applies. The official sheet distinguishes these situations, so a document that is suitable for a mother's application may not be sufficient for a guardian's application. Relationship evidence is especially important when surnames, addresses or guardianship arrangements have changed.",
      "Where more than one dependent child is included, prepare an individual age document for each child instead of assuming that a family document proves every date of birth. Death and disability certificates should come from the competent registrar or medical authority and should clearly identify the relevant parent. The bank account used for the claim should be the account permitted by the current service procedure; ask how the account must be titled when the beneficiary is a minor. If guardianship is informal or disputed, obtain official guidance before applying. This prevents the application from reaching verification without the legal relationship evidence needed to make a payment decision for a child.",
    ],
  },
  "construction-worker-shagun-scheme-punjab": {
    heading: "Planning the Shagun claim around the marriage deadline",
    paragraphs: [
      "The three-month post-marriage filing period makes preparation before the ceremony sensible even though the final application follows the marriage. The registered worker can check BOCW membership and contributions, confirm the bride's date-of-birth evidence, and ask which local authority will provide the required marriage confirmation. After the ceremony, obtain the registered marriage certificate without delay and preserve clear marriage photographs. If a certificate contains a name or date different from the Board record, seek correction immediately. Waiting until the final week can leave too little time to register the marriage, correct a record and submit Form 35.",
      "The benefit concerns an eligible first marriage and is limited to the marriages of up to two daughters. A registered female construction worker may apply for her own eligible marriage, but registration alone should not be treated as automatic approval; membership, contribution and documentary conditions still apply. Before submission, compare the BOCW registration number, beneficiary name and bank details with Board records. Ask for a dated acknowledgement showing that the claim was received within the permitted period. If an authorized office refuses a timely application because of a correctable document issue, request the deficiency in writing so the applicant has a reliable record of what must be supplied and when.",
    ],
  },
  "construction-worker-scholarship-punjab": {
    heading: "Building the education record for a stipend claim",
    paragraphs: [
      "The institution is central to this application because it verifies the student's current admission, previous result and hostel status. Request certificates carrying the student's full name, class or course, academic session, institution name, signature, stamp and date. The previous-class certificate should show that the student passed, since the detailed Board conditions say assistance is not granted in a fail case. If a student changed institutions, make sure the previous result and present admission records use consistent identity details. A hostel claim should be supported by the institution's hostel certificate rather than a private rent receipt unless the Board expressly accepts another form of proof.",
      "Published assistance varies widely from early school classes to professional study, which makes correct course classification important. Medical, engineering, ITI, polytechnic, graduation and postgraduate cases should be entered under the category recognized by the current Board system. The available official rate table is dated from 2016; it establishes the scheme's structure but may not settle the amount payable for the present academic year. Ask the Board or application centre to confirm the current rate, deadline and whether a fresh application is required every year. Retain the submitted education certificates because they can help resolve a query about class progression, hostel status or a duplicate-benefit database match.",
    ],
  },
  "construction-worker-maternity-benefit-punjab": {
    heading: "Membership timing and birth documents",
    paragraphs: [
      "This claim depends on dates that can be checked objectively: the start of BOCW membership, contribution history, child's birth date and application date. The published conditions require at least six months of membership before birth, regular contributions and submission within three months after birth. Review the worker's Board record early rather than discovering a contribution gap close to the deadline. Form 46 also asks whether the child is the first or second, so the family should give accurate information about earlier children. The limitation is part of eligibility and should not be bypassed by leaving a required field incomplete.",
      "The Registrar-issued birth certificate and the village Sarpanch certificate are listed as mandatory in the form reviewed for this guide. Check that the child's and parents' names are spelled consistently and that the birth date is correct. Bank details should include the account number, branch and IFSC exactly as recorded by the bank. The official form was last revised in October 2017, while the Board summary supplies the listed male and female benefit amounts. Because an operational instruction may change faster than a downloadable form, confirm the current amount, submission channel and deadline at the time of filing, but do not delay that confirmation until after the published three-month window.",
    ],
  },
  "construction-worker-tools-kit-punjab": {
    heading: "Training proof, eligible tools and purchase bills",
    paragraphs: [
      "The Tool Kit Scheme connects three records: active BOCW beneficiary status, completion of qualifying Skill Upgradation or Recognition of Prior Learning training, and the purchase of occupational tools. A worker should confirm that the completed training appears in the Board's accepted record before buying items primarily for reimbursement. The tools should have a clear connection to the worker's trained trade. General household goods, personal electronics or an unexplained mixed invoice may be difficult to justify. If eligibility is uncertain, show the proposed item list to the authorized office and ask for current guidance before spending money.",
      "Because payment is reimbursement, preserve itemized bills showing the seller, date, description, quantity and price. Cash memos with no item description or buyer connection may create a verification problem. Upload or submit the complete bill together with training proof, registration details, contribution record and bank information. The Board material describes assistance up to ₹5,000 and a further benefit after three years, but both should be confirmed against current instructions. Keep the purchased tools and original bills available until the application is decided, and retain the acknowledgement so a subdivisional verification query can be linked to the correct claim rather than filed as a duplicate.",
    ],
  },
};
