export const schemeSeo: Record<string, { title: string; description: string; primaryKeyword: string }> = {
  "mukh-mantri-mawan-dheeyan-satkar-yojana": { title: "Mawan Dhiyan Satkar Yojana 2026: ₹1,000–₹1,500", description: "Check Mawan Dhiyan Satkar Yojana eligibility, exclusions, documents, free registration and Aadhaar-linked DBT guidance for Punjab women.", primaryKeyword: "Mawan Dhiyan Satkar Yojana 2026" },
  "old-age-pension-punjab": { title: "Old Age Pension Punjab 2026: Eligibility & Apply", description: "Check Punjab old age pension eligibility, documents, application channels and official verification guidance for senior residents.", primaryKeyword: "old age pension Punjab" },
  "widow-destitute-pension-punjab": { title: "Widow Pension Punjab 2026: Eligibility & Documents", description: "Understand Punjab widow and destitute women pension eligibility, situation-specific documents and official application routes.", primaryKeyword: "widow pension Punjab" },
  "dependent-children-pension-punjab": { title: "Dependent Children Pension Punjab 2026: Apply Guide", description: "Check Punjab dependent children pension eligibility, guardian requirements, documents and official application channels.", primaryKeyword: "dependent children pension Punjab" },
  "disabled-person-pension-punjab": { title: "Disabled Person Pension Punjab 2026: Eligibility & Apply", description: "Punjab disabled person pension guide covering disability proof, guardian applications, documents, fees and eligibility checks.", primaryKeyword: "disabled person pension Punjab" },
  "national-family-benefit-scheme-punjab": { title: "National Family Benefit Scheme Punjab 2026: Apply Guide", description: "Check Punjab National Family Benefit Scheme eligibility after a primary earner's death, BPL evidence and required documents.", primaryKeyword: "National Family Benefit Scheme Punjab" },
  "construction-worker-shagun-scheme-punjab": { title: "Punjab BOCW Shagun Scheme 2026: ₹31,000 Guide", description: "Check Punjab construction worker Shagun Scheme eligibility, marriage documents, three-month deadline and official Form 35.", primaryKeyword: "Punjab BOCW Shagun Scheme" },
  "construction-worker-scholarship-punjab": { title: "Punjab BOCW Scholarship 2026: Eligibility & Documents", description: "Punjab construction worker education stipend guide covering eligible study, institution certificates, hostel proof and rates.", primaryKeyword: "Punjab BOCW scholarship" },
  "construction-worker-maternity-benefit-punjab": { title: "Punjab BOCW Maternity Benefit 2026: Apply Guide", description: "Check Punjab construction worker maternity benefit eligibility, membership period, birth documents and filing deadline.", primaryKeyword: "Punjab BOCW maternity benefit" },
  "construction-worker-tools-kit-punjab": { title: "Punjab BOCW Tool Kit Scheme 2026: Eligibility & Claim", description: "Understand Punjab BOCW tool reimbursement, training requirements, purchase bills, eligibility and the official claim process.", primaryKeyword: "Punjab BOCW Tool Kit Scheme" },
};
